name: CI

on:
  push:
    branches:
      - next

  pull_request:
    branches:
      - next

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install pnpm
      run: corepack enable

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Run test cases
      run: |
        echo "PR Message github.event.number: ${{ github.event.number }}"
        pr_number=${{ github.event.number }}
        files_url="https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number/files"
        files_response=$(curl -sSL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $files_url)
        files_changed=$(echo "$files_response" | jq -r '.[].filename')
        echo "PR files: $files_changed"
        component=$(echo "$files_changed" |  grep -E -i 'src\/packages\/([a-z]+)(\/[a-z_\.]*)*' | sed -E 's/src\/packages\/([a-z]+)(\/[a-z_\.]*)*/\1/i' | awk 'END{print}')
        npm test -- $component

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install pnpm
      run: corepack enable

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Build NutUI-React
      run: npm run build

    - name: Build NutUI-React-Taro
      run: npm run build:taro
    
    - name: Build NutUI-React Demo
      run: npm run build:site
